// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-kyaLLO6n4S6vN8YZUWt36yAc-_vkW8',
    appId: '1:1049578725587:web:c4dc5f778298e174d73426',
    messagingSenderId: '1049578725587',
    projectId: 'gasalertapp-001',
    authDomain: 'gasalertapp-001.firebaseapp.com',
    storageBucket: 'gasalertapp-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BJv5xpp-d60oT2OZ-x6vnB4A44GDunQ',
    appId: '1:1049578725587:android:d9f3c1e80070e8ddd73426',
    messagingSenderId: '1049578725587',
    projectId: 'gasalertapp-001',
    storageBucket: 'gasalertapp-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_DrTYphCCGZhRwBmZKoBvvgpRORJ1rm0',
    appId: '1:1049578725587:ios:bc1db14832d657ead73426',
    messagingSenderId: '1049578725587',
    projectId: 'gasalertapp-001',
    storageBucket: 'gasalertapp-001.firebasestorage.app',
    iosBundleId: 'com.example.gasalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_DrTYphCCGZhRwBmZKoBvvgpRORJ1rm0',
    appId: '1:1049578725587:ios:bc1db14832d657ead73426',
    messagingSenderId: '1049578725587',
    projectId: 'gasalertapp-001',
    storageBucket: 'gasalertapp-001.firebasestorage.app',
    iosBundleId: 'com.example.gasalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT-kyaLLO6n4S6vN8YZUWt36yAc-_vkW8',
    appId: '1:1049578725587:web:32f76d84b5f5fc76d73426',
    messagingSenderId: '1049578725587',
    projectId: 'gasalertapp-001',
    authDomain: 'gasalertapp-001.firebaseapp.com',
    storageBucket: 'gasalertapp-001.firebasestorage.app',
  );
}
